#casks - for extra funtionality
tap "homebrew/bundle"
tap "thoughtbot/formulae"
tap "buo/cask-upgrade"                  # to upgrade all the apps installed by homebrew cask
tap "homebrew/core"
tap "homebrew/services"
tap "caskroom/versions"                 # for java 1.8
tap "caskroom/cask"
tap "universal-ctags/universal-ctags"

# Set applications directory
cask_args appdir: "/Applications"

# Unix tools
brew "universal-ctags", args: ["HEAD"]
brew "git"
brew "openssl"
brew "readline"     # Utilities that one needs.... 

# GitHub
brew "hub"

# Programming language prerequisites and package managers
brew "libyaml"              # should come after openssl
brew "coreutils"

# we're an aws shop...
brew "awscli"

# need the latest version of java and maven
cask "java"  unless system "/usr/libexec/java_home --failfast"
brew "maven"

# development tools
cask "sublime-text"     # programming editor
cask "intellij-idea"    # manage jetbrains IDEs with their toolbox
cask "sourcetree"       # Git client
cask "docker"           # docker - containerise all the things
cask "kitematic"        # UI for working with docker
cask "iterm2"           # item - terminal alternative 
cask "mysqlworkbench"   # mysql work bench
cask "sequel-pro"       # ui for database management
cask "postman"          # Postman - for API development and testing

# video viewer
cask "vlc"

# slack
cask "slack"

# window management from the keyvoard
cask "spectacle"

# combine chat and messaging into one application (slack/whatsapp/etc)
cask "franz"
